# Generated by Django 6.1 on 2026-09-12 02:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('summary', models.TextField()),
                ('context', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('contributions', models.JSONField(default=list)),
                ('technologies', models.JSONField(default=list)),
                ('project_url', models.URLField()),
                ('image_path', models.CharField(max_length=255)),
                ('started_on', models.DateField()),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('achievement', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_on', 'title'],
            },
        ),
    ]
