# Generated by Django 6.1 on 2026-09-12 02:36

from datetime import date

from django.db import migrations


PROJECT_DATA = [
    {
        "title": "SisPro",
        "slug": "sispro",
        "summary": "Women Safety and Smart Protection Platform",
        "context": "SISTECH 2026 Final Project",
        "role": "Product Manager",
        "contributions": [
            "Co-led product management in a ten-member "
            "cross-functional team.",
            "Translated user safety concerns into product "
            "requirements, priorities, and execution plans.",
            "Defined the minimum viable product for Safe Route "
            "and Risk Prediction, Anonymous Reporting, "
            "Emergency SOS, and Journey Monitoring.",
            "Coordinated user research and prototype validation, "
            "then translated usability findings into prioritized "
            "onboarding and interface improvements.",
        ],
        "technologies": [
            "Product Management",
            "User Research",
            "Product Requirements",
            "Prototype Validation",
        ],
        "project_url": "https://sister-protect.vercel.app/",
        "image_path": "img/projects/sispro.webp",
        "started_on": date(2026, 7, 1),
        "ended_on": date(2026, 8, 31),
        "achievement": "Best Final Project at SISTECH 2026",
        "is_featured": True,
    },
    {
        "title": "RumputSehat EWS",
        "slug": "rumputsehat-ews",
        "summary": (
            "Multimodal Early-Warning System for Ice-Ice Disease"
        ),
        "context": "RISTEK Fasilkom UI Datathon 2026",
        "role": "Full-stack and AI Contributor",
        "contributions": [
            "Conducted problem identification and requirements "
            "analysis for Indonesian seaweed farming, then "
            "translated the findings into a multimodal "
            "early-warning system concept for ice-ice disease.",
            "Co-developed a multimodal AI early-warning system "
            "that combines visual and environmental information "
            "for seaweed farming.",
            "Contributed to the frontend, backend, and integration "
            "of the AI model into the application.",
        ],
        "technologies": [
            "Multimodal AI",
            "Data Annotation",
            "Full-stack Integration",
        ],
        "project_url": (
            "https://rumputsehat-ews-datathon2026.streamlit.app/"
        ),
        "image_path": "img/projects/rumputsehat.webp",
        "started_on": date(2026, 5, 1),
        "ended_on": None,
        "achievement": "Semifinalist",
        "is_featured": False,
    },
    {
        "title": "Sortify",
        "slug": "sortify",
        "summary": "AI Waste Detector and Classification Web App",
        "context": "HackVidia - Arkavidia National Hackathon",
        "role": "Frontend Developer",
        "contributions": [
            "Helped design a web application that identifies "
            "household waste and provides disposal guidance and "
            "nearby facility recommendations.",
            "Developed the React.js frontend based on Figma "
            "designs and high-fidelity prototypes.",
            "Implemented interfaces for waste scanning, "
            "classification results, disposal instructions, and "
            "location-based facility discovery.",
        ],
        "technologies": [
            "React.js",
            "Django",
            "TensorFlow and Keras",
            "MobileNet",
        ],
        "project_url": "https://sortifyai.netlify.app/",
        "image_path": "img/projects/sortify.webp",
        "started_on": date(2026, 1, 1),
        "ended_on": None,
        "achievement": "",
        "is_featured": False,
    },
]


def add_project_data(apps, schema_editor):
    """Add the initial portfolio projects to the database."""
    Project = apps.get_model("main", "Project")

    for project_data in PROJECT_DATA:
        Project.objects.create(**project_data)


def remove_project_data(apps, schema_editor):
    """Remove only the projects added by this migration."""
    Project = apps.get_model("main", "Project")
    project_slugs = [
        project_data["slug"]
        for project_data in PROJECT_DATA
    ]
    Project.objects.filter(slug__in=project_slugs).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_project"),
    ]

    operations = [
        migrations.RunPython(
            add_project_data,
            remove_project_data,
        ),
    ]