# Generated by Django 6.1 on 2026-09-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_project_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='ended_at',
            new_name='ended_on',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='started_at',
            new_name='started_on',
        ),
    ]
