# Generated by Django 6.1 on 2026-09-12 14:05

from datetime import date

from django.db import migrations


EXPERIENCE_DATA = [
    {
        "title": "Teaching Assistant for Discrete Mathematics 1",
        "organization": (
            "Faculty of Computer Science, Universitas Indonesia"
        ),
        "description": (
            "Grade quizzes and assess students' understanding of "
            "Discrete Mathematics concepts. Conduct teaching assistance "
            "sessions and supervise students during quizzes."
        ),
        "category": "part-time",
        "started_on": date(2026, 8, 1),
        "ended_on": None,
    },
    {
        "title": "Product Manager Mentee, SISTECH 2026",
        "organization": (
            "RISTEK, Faculty of Computer Science, "
            "Universitas Indonesia"
        ),
        "description": (
            "Developed and refined product requirements for a final "
            "project with a 10-member cross-functional team. Translated "
            "identified problems into requirements and collaborated "
            "across roles to align project execution."
        ),
        "category": "program",
        "started_on": date(2026, 7, 1),
        "ended_on": date(2026, 8, 31),
    },
    {
        "title": "Product Management Academy Staff",
        "organization": "COMPFEST, Universitas Indonesia",
        "description": (
            "Supported mentor and speaker outreach through LinkedIn. "
            "Participated in internal product management learning "
            "sessions and supported academy participants."
        ),
        "category": "volunteer",
        "started_on": date(2026, 6, 1),
        "ended_on": None,
    },
    {
        "title": "Product Management Intern",
        "organization": (
            "BEM Faculty of Computer Science, Universitas Indonesia"
        ),
        "description": (
            "Developed a product proposal and prototype from a "
            "real-world problem. Defined the product concept, features, "
            "and value proposition while collaborating with designers "
            "and software engineers."
        ),
        "category": "internship",
        "started_on": date(2025, 9, 1),
        "ended_on": date(2025, 12, 31),
    },
]


def add_experience_data(apps, schema_editor):
    """Add experience information from the portfolio owner's CV."""
    Experience = apps.get_model("main", "Experience")

    # Remove the temporary Tutorial 2 record.
    Experience.objects.filter(
        title="Mathematics Discrete 1 Teaching Assistant"
    ).delete()

    for experience_data in EXPERIENCE_DATA:
        defaults = experience_data.copy()
        title = defaults.pop("title")

        Experience.objects.update_or_create(
            title=title,
            defaults=defaults,
        )


def remove_experience_data(apps, schema_editor):
    """Remove only the experience records added here."""
    Experience = apps.get_model("main", "Experience")
    titles = [item["title"] for item in EXPERIENCE_DATA]

    Experience.objects.filter(title__in=titles).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_experience_options_experience_organization_and_more"),
    ]

    operations = [
        migrations.RunPython(
            add_experience_data,
            remove_experience_data,
        ),
    ]