# Generated by Django 6.1 on 2026-09-12 14:25

from django.db import migrations, models


EXPERIENCE_RESPONSIBILITIES = {
    "Teaching Assistant for Discrete Mathematics 1": [
        (
            "Grade quizzes and assess students' understanding "
            "of Discrete Mathematics concepts."
        ),
        (
            "Conduct teaching assistance sessions to explain "
            "course materials and clarify students' questions."
        ),
        (
            "Supervise students during quiz sessions to ensure "
            "the assessments run smoothly and follow course guidelines."
        ),
    ],
    "Product Manager Mentee, SISTECH 2026": [
        (
            "Developed and refined product requirements, including "
            "Product Requirement Documents, for a final project "
            "involving a 10-member cross-functional team."
        ),
        (
            "Contributed to product planning and feature definition "
            "by translating identified problems into product "
            "requirements and solutions."
        ),
        (
            "Collaborated with team members across different roles "
            "to align product direction, requirements, and execution."
        ),
    ],
    "Product Management Academy Staff": [
        (
            "Assist in mentor and speaker outreach by contacting "
            "potential candidates through LinkedIn."
        ),
        (
            "Participate in internal product management "
            "learning sessions."
        ),
        (
            "Support academy operations and assist participants "
            "throughout their learning journey."
        ),
    ],
    "Product Management Intern": [
        (
            "Developed a product proposal and prototype based on "
            "a given real-world problem."
        ),
        (
            "Defined the product concept, features, and value "
            "proposition from the initial problem analysis."
        ),
        (
            "Collaborated with UI/UX designers and software engineers "
            "to align product vision and execution."
        ),
    ],
}


def add_responsibilities(apps, schema_editor):
    """Add responsibility points to the existing experiences."""
    Experience = apps.get_model("main", "Experience")

    for title, responsibilities in EXPERIENCE_RESPONSIBILITIES.items():
        Experience.objects.filter(title=title).update(
            responsibilities=responsibilities,
        )


def remove_responsibilities(apps, schema_editor):
    """Remove the responsibility points added here."""
    Experience = apps.get_model("main", "Experience")

    Experience.objects.filter(
        title__in=EXPERIENCE_RESPONSIBILITIES,
    ).update(responsibilities=[])


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_add_experience_data"),
    ]

    operations = [
        # Add the field before filling it with data.
        migrations.AddField(
            model_name="experience",
            name="responsibilities",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(
            add_responsibilities,
            remove_responsibilities,
        ),
    ]
