# Generated by Django 6.1 on 2026-09-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_project_options_project_starred_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-started_on', 'title']},
        ),
    ]
